32 VARIABLE X
24 VARIABLE Y
1 VARIABLE DX
-1 VARIABLE DY
1 VARIABLE LEN

: PL X @ Y @ ABS 47 MOD 3 PLOT ;

: !+ OVER @ + SWAP ! ;

: STEP X DX @ !+ Y DY @ !+ ;

: TURN DX @ NEGATE DY @ DX ! DY ! ;

: DEMO BEGIN LEN @ 0 DO PL STEP LOOP TURN LEN 1 !+ 0 UNTIL ; 
